import 'package:fooder/presentation/view/home_view/home_screen/restaurant/restaurant_model.dart';

final List<Restaurant> mockRestaurants = [
  Restaurant(
    id: '1',
    name: 'The Rustic Spoon',
    imageUrl: 'assets/images/restaurants/restaurant1.jpg',
    rating: 4.5,
    reviewCount: 120,
    cuisineType: 'Tanzanian',
    description: 'Cozy restaurant with farm-to-table cuisine.',
    specialOffer: '10% off for lunch',
    location: 'Dar es Salaam, Kinondoni Street',
  ),
  Restaurant(
    id: '2',
    name: 'Sushi Haven',
    imageUrl: 'assets/images/restaurants/restaurant2.jpeg',
    rating: 4.8,
    reviewCount: 200,
    cuisineType: 'Japanese',
    description: 'Fresh and authentic sushi experience.',
    location: 'Arusha, Njiro Road',
  ),
  Restaurant(
    id: '3',
    name: 'La Trattoria',
    imageUrl: 'assets/images/restaurants/restaurant3.jpeg',
    rating: 4.3,
    reviewCount: 150,
    cuisineType: 'Italian',
    description: 'Family-owned Italian restaurant with homemade pasta.',
    specialOffer: 'Free dessert with any main course',
    location: 'Zanzibar, Stone Town',
  ),
  Restaurant(
    id: '4',
    name: 'Spice Route',
    imageUrl: 'assets/images/restaurants/restaurant4.jpeg',
    rating: 4.6,
    reviewCount: 180,
    cuisineType: 'Indian',
    description: 'Authentic Indian cuisine with a modern twist.',
    location: 'Mwanza, Capri Point',
  ),
  Restaurant(
    id: '5',
    name: 'Green Leaf Cafe',
    imageUrl: 'assets/images/restaurants/restaurant1.jpg',
    rating: 4.2,
    reviewCount: 90,
    cuisineType: 'Vegan',
    description: 'Healthy and delicious plant-based options.',
    specialOffer: '15% off for first-time visitors',
    location: 'Dodoma, City Center',
  ),
];